# Generated by Django 3.2.5 on 2021-07-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210726_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='favorited',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
