# Generated by Django 3.2.5 on 2021-07-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210728_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default='Subject', max_length=250),
        ),
    ]
