# Generated by Django 3.2.5 on 2021-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, default='Subject', max_length=250, null=True),
        ),
    ]
